services:
  mysqldb:
    container_name: mysqlcontainer
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysqlvolume:/var/lib/mysql

  adminer:
    container_name: adminercontainer
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

volumes:
  mysqlvolume:
